security:
    access_denied_url: /%locale%/403
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: front_home
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
        
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    # ROLE_SUPER_VISITOR is a fake ROLE_SUPER_ADMIN
    role_hierarchy:
        ROLE_USER:
        ROLE_CONTRIBUTOR:       ROLE_USER
        ROLE_MODERATOR:         ROLE_CONTRIBUTOR
        ROLE_ADMIN:             ROLE_MODERATOR
        ROLE_SUPER_VISITOR:     ROLE_ADMIN
        ROLE_SUPER_ADMIN:       ROLE_SUPER_VISITOR
    access_control:
        - { path: ^/%app_locales%, roles: PUBLIC_ACCESS }
        - { path: ^/%app_locales%/contrib, roles: ROLE_CONTRIBUTOR }
        - { path: ^/%app_locales%/message, roles: ROLE_CONTRIBUTOR }
        - { path: ^/%app_locales%/my-contribs, roles: ROLE_CONTRIBUTOR }
        - { path: ^/%app_locales%/my-translations, roles: ROLE_CONTRIBUTOR }
        - { path: ^/%app_locales%/back, roles: ROLE_MODERATOR }
        - { path: ^/%app_locales%/back/content, roles: ROLE_ADMIN }
        - { path: ^/%app_locales%/back/lang, roles: ROLE_SUPER_VISITOR }
        - { path: ^/%app_locales%/back/translation, roles: ROLE_SUPER_VISITOR }
