back_translation_situ_create:
    path:       /{locale}/{back}/translation/{referentId}/{langId}/{id}
    controller: App\Controller\TranslationController::createTranslate
    methods:    ['GET', 'POST']
    defaults:
        id: null
front_translation_create:
    path:       /{locale}/translation/{referentId}/{langId}/{id}
    controller: App\Controller\TranslationController::createTranslate
    methods:    ['GET', 'POST']
    defaults:
        id: null